services:
  - type: web
    name: aimec-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Variables de base de datos (Railway)
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: DB_SCHEMA
        value: public
      # JWT
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      # AWS (para dominio y almacenamiento)
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      # Almacenamiento de im치genes (AWS S3)
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_S3_REGION
        value: us-east-1
      # CORS
      - key: CORS_ORIGIN
        value: https://tu-dominio.com,https://tu-app.vercel.app
      # Logging
      - key: LOG_LEVEL
        value: info
      # Rate limiting
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      # Swagger
      - key: SWAGGER_TITLE
        value: AIMEC API
      - key: SWAGGER_VERSION
        value: 1.0.0
      - key: SWAGGER_DESCRIPTION
        value: API REST para el sistema de gesti칩n de productos industriales AIMEC
      # Encriptaci칩n
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      # Validaci칩n
      - key: VALIDATION_STRICT
        value: true
