service: aimec-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  environment:
    DB_HOST: ${env:DB_HOST, 'localhost'}
    DB_PORT: ${env:DB_PORT, '5432'}
    DB_NAME: ${env:DB_NAME, 'aimec_db'}
    DB_USER: ${env:DB_USER, 'postgres'}
    DB_PASSWORD: ${env:DB_PASSWORD, 'password'}

functions:
  api:
    handler: handler.handler
    events:
      - http: ANY /{proxy+}
    environment:
      DB_HOST: ${env:DB_HOST, 'localhost'}
      DB_PORT: ${env:DB_PORT, '5432'}
      DB_NAME: ${env:DB_NAME, 'aimec_db'}
      DB_USER: ${env:DB_USER, 'postgres'}
      DB_PASSWORD: ${env:DB_PASSWORD, 'password'}

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3750
    noPrependStageInUrl: true
    host: 0.0.0.0
    cors: true
    corsAllowOrigin: "*"
    corsAllowHeaders: "Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token"
    corsAllowCredentials: true