service: aimec-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

functions:
  api:
    handler: handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-offline